# config.yaml for superresolution.py
batch_size: 8
use_batchnorm: true
loss_type: mse  # mse or lpips
adam_lr: 0.0001  # Add this line for Adam learning rate
resume_weights_path: null
num_epochs: 100  # Number of epochs to train
train_batches_to_load: 125  # Number of training batches per epoch
validation_batches_to_load: 10  # Number of validation batches per epoch
max_samples: null
overfit_one_batch: false
visualize_every_n_epochs: 10  # Number of epochs between visualizations
